### ISSUE TITLE
doesn't work on PC, only on Mac

### ISSUE THREAD

**Issue by Mooniakz** [jcw-os/google-meet-ptt#1]
Hello! 

the way you search for the mute button is:
element.dataset.tooltip.includes('⌘ + D')

that only works on Mac. 
you should also consider searching for 'ctrl + d' , that's exactly how the shortcut reads on the tooltip on PC.

Thank you!

**Comment by jackcw** [comment]
Thank you @Mooniakz I have pushed up a change to the Chrome Web Store and is pending review. I have tested the fix on a windows device and works. Will close this but if the issue persists after you update to v1.0.2 let me know.
