### ISSUE TITLE
Can't use spacebar in the chat without unmuting/muting

### ISSUE THREAD

**Issue by fmlatghor** [jcw-os/google-meet-ptt#10]
I'm using ff, so I haven't checked to see if this is a problem in Chrome as well.

**Comment by mickeyreiss** [comment]
I am seeing this in Chrome as well. One possible fix is to simplify the `chatOpen` logic from this:
https://github.com/jcw-os/google-meet-ptt/blob/75febce451a70331f22f898c9d99e9b41bdec788/src/content_script.ts#L64-L71

to this:
```typescript
    // Check if the chat window is open
    chatOpen = document.querySelector("[name=chatTextInput]");
```

**Comment by willi84** [comment]
@mickeyreiss could u create a PR?
