### ISSUE TITLE
Extension not working in the new May 2021 meet version

### ISSUE THREAD

**Issue by niccord** [jcw-os/google-meet-ptt#19]
I don't know how to identify the new version of Google Meet (it will be the new standard after May 2021) but this extension doesn't seem to work anymore in this new version.

That's probably because they changed the `data-tooltip` info.

I would like to provide a PR for this issue.

**Comment by jackcw** [comment]
I have pushed up a hacky fix into [feat/new-meet-ui](https://github.com/jcw-os/google-meet-ptt/tree/feat/new-meet-ui) if you want to check it out. Feel free to do something better but hopefully a bit of an understanding where i got the pieces from. I will look to do a deployment by sunday if you wanted to make changes @niccord

**Comment by niccord** [comment]
I am always sceptical about naming methods `old` and `new` because what if google puts out a new version? Will you call it `new-new`? 😂 

Besides that, I looked at your code and I did the same: check the `aria-label` instead of the `dataset.tooltip`.

Don't forget to check the `aria-label` value using `muteButtonTooltip` 😉

**Comment by jackcw** [comment]
Yeh i do agree, however the new ui will become the only ui soon and then i will just remove the old/new labels.

will add that last bit for muteButtonTooltip and get it deployed
