### ISSUE TITLE
Microsoft Chromium Edge release

### ISSUE THREAD

**Issue by MarcAnt01** [jcw-os/google-meet-ptt#2]
Hi, this extension is totally working on the new Microsoft Edge. Can you publish it in its proper store? https://microsoftedge.microsoft.com/addons/Microsoft-Edge-Extensions-Home?hl=en-US

**Comment by jackcw** [comment]
Currently in the Microsoft review cycle

**Comment by jackcw** [comment]
It has now been approved for the Microsoft store https://microsoftedge.microsoft.com/addons/detail/ofocadnjhfmcekamdnifdkpcibfnalce
