### ISSUE TITLE
Change color of the button when hovering with the pointer

### ISSUE THREAD

**Issue by MarcAnt01** [jcw-os/google-meet-ptt#4]
![image](https://user-images.githubusercontent.com/43090263/82816164-edccde00-9e9a-11ea-8874-4c9aa99fd0b3.png)

**Comment by jackcw** [comment]
Added with branch _feat/add-hover-css_

**Comment by MarcAnt01** [comment]
> Added with branch _feat/add-hover-css_

Thank you
